services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: subh99kr/doctubeai-frontend:latest

    container_name: doctubeai-frontend

    env_file:
      - .env

    ports:
      - "5173:5173"

    restart: unless-stopped