services:
  frontend:
    image: doctubeai-react:v1

    container_name: doctubeai-react

    ports:
      - "5173:5173"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

  